title: abapOpenChecks
highlighter: rouge
collections:
  checks:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"